### ISSUE TITLE
Query about GNN-seg and GNN-plain

### ISSUE THREAD

**Issue by shhs29** [Xi-yuanWang/GLASS#1]
Hi,

I am wondering what is the difference between GNN-seg and GNN-plain mentioned in the paper. I could also not find the implementation of the same in the code.  

Thanks a lot in advance,
Shweta Ann Jacob

**Comment by Xi-yuanWang** [comment]
Dear Shweta,

As shown in the ablation analysis section (page 8 in [our paper](https://openreview.net/pdf?id=XLxhEjKNbXj)), GNN-plain means GLASS without labeling trick. You can use the following command to run GNN-plain.
```
python GLASSTest.py --use_nodeid --use_seed --repeat 10 --device $gpu_id --dataset $dataset
```
GNN-seg is GNN-plain working on the segregated target subgraph rather than the whole graph. I will release the implementation of GNN-seg later.  

Sincerely,
Xiyuan Wang

**Comment by shhs29** [comment]
Hi Xiyuan,

Thanks a lot for the quick response! Looking forward to it.

Closing this issue as it is resolved.

**Comment by Xi-yuanWang** [comment]
Dear Shweta,

We have released the implementation of GNN-seg. You can use the following command.

```
python GNNSeg.py --test  --repeat 10 --device $gpu_id --dataset $dataset
```

Sincerely,
Xiyuan Wang

**Comment by shhs29** [comment]
Hi Xiyuan,

Thanks a lot for letting me know!
